"""initial schema

Revision ID: 8cdb329ee0b8
Revises:
Create Date: 2026-08-20 00:54:53.982585
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8cdb329ee0b8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "egress_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("egress_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_egress_log_ts"), ["ts"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_paper_id"), ["paper_id"], unique=False
        )
        batch_op.create_index(
            "ix_jobs_pick", ["state", "kind", "priority", "id"], unique=False
        )

    op.create_table(
        "papers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("work_key", sa.String(length=512), nullable=False),
        sa.Column("pdf_path", sa.Text(), nullable=False),
        sa.Column("pdf_bytes", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("pipeline_version", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_papers_content_sha256"), ["content_sha256"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_papers_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_papers_work_key"), ["work_key"], unique=False
        )

    op.create_table(
        "projection_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("n_fit", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("model_path", sa.Text(), nullable=True),
        sa.Column("fit_matrix_path", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("fitted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projection_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projection_runs_is_active"), ["is_active"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=True),
        sa.Column("canonical_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_tags_status"), ["status"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chunks_paper_id"), ["paper_id"], unique=False
        )
        batch_op.create_index("ix_chunks_paper_ord", ["paper_id", "ord"], unique=False)

    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("hdbscan_label", sa.Integer(), nullable=False),
        sa.Column("llm_label", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("centroid_json", sa.Text(), nullable=True),
        sa.Column("top_terms_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["projection_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clusters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clusters_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "doc_vectors",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("row_idx", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id"),
        sa.UniqueConstraint("row_idx"),
    )
    with op.batch_alter_table("doc_vectors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doc_vectors_model_id"), ["model_id"], unique=False
        )

    op.create_table(
        "markdown_docs",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("md_path", sa.Text(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("parser", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("quality_report_json", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id"),
    )
    op.create_table(
        "paper_meta",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authors_json", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("arxiv_id", sa.String(length=64), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("keywords_json", sa.Text(), nullable=True),
        sa.Column("field_sources_json", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id"),
    )
    with op.batch_alter_table("paper_meta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_meta_arxiv_id"), ["arxiv_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_paper_meta_doi"), ["doi"], unique=False)
        batch_op.create_index(batch_op.f("ix_paper_meta_year"), ["year"], unique=False)

    op.create_table(
        "paper_tags",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id", "tag_id"),
    )
    op.create_table(
        "projections",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("z", sa.Float(), nullable=False),
        sa.Column("is_transformed", sa.Boolean(), nullable=False),
        sa.Column("off_manifold", sa.Float(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["projection_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "paper_id"),
    )
    with op.batch_alter_table("projections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projections_cluster_id"), ["cluster_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projections_cluster_id"))

    op.drop_table("projections")
    op.drop_table("paper_tags")
    with op.batch_alter_table("paper_meta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_meta_year"))
        batch_op.drop_index(batch_op.f("ix_paper_meta_doi"))
        batch_op.drop_index(batch_op.f("ix_paper_meta_arxiv_id"))

    op.drop_table("paper_meta")
    op.drop_table("markdown_docs")
    with op.batch_alter_table("doc_vectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doc_vectors_model_id"))

    op.drop_table("doc_vectors")
    with op.batch_alter_table("clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clusters_run_id"))

    op.drop_table("clusters")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_paper_ord")
        batch_op.drop_index(batch_op.f("ix_chunks_paper_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_status"))
        batch_op.drop_index(batch_op.f("ix_tags_slug"))

    op.drop_table("tags")
    op.drop_table("settings")
    with op.batch_alter_table("projection_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projection_runs_is_active"))

    op.drop_table("projection_runs")
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_papers_work_key"))
        batch_op.drop_index(batch_op.f("ix_papers_status"))
        batch_op.drop_index(batch_op.f("ix_papers_content_sha256"))

    op.drop_table("papers")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_pick")
        batch_op.drop_index(batch_op.f("ix_jobs_paper_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_kind"))

    op.drop_table("jobs")
    with op.batch_alter_table("egress_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_egress_log_ts"))

    op.drop_table("egress_log")
    # ### end Alembic commands ###
